import jsPDF from 'jspdf';

// Helper function to add company header
function addCompanyHeader(doc: jsPDF, title: string) {
  // Primary color: hsl(258.3, 70.2%, 60.2%) converted to RGB
  // Using a purple shade that matches the theme
  const primaryR = 139;
  const primaryG = 92;
  const primaryB = 246;
  
  // Header background
  doc.setFillColor(primaryR, primaryG, primaryB);
  doc.rect(0, 0, 210, 35, 'F');
  
  // Company name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Skincare ERP', 20, 22);
  
  // Document title (centered)
  doc.setFontSize(18);
  doc.text(title, 105, 22, { align: 'center' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  return 45; // Return starting Y position after header
}

// Helper function to add footer
function addFooter(doc: jsPDF, pageNumber: number, totalPages: number) {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Generated by Skincare ERP • Page ${pageNumber} of ${totalPages}`,
    105,
    pageHeight - 10,
    { align: 'center' }
  );
  doc.setTextColor(0, 0, 0);
}

export function generateSalesInvoicePDF(sale: any) {
  const doc = new jsPDF();
  let totalPages = 1;

  // Add header
  let y = addCompanyHeader(doc, 'Sales Invoice');

  // Sale details
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Invoice Details', 20, y);
  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.text(`Invoice #: ${sale.id.slice(0, 8).toUpperCase()}`, 20, y);
  y += 6;
  doc.text(`Date: ${new Date(sale.sale_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 20, y);
  y += 6;
  doc.text(`Customer: ${sale.customers?.name || 'Walk-in Customer'}`, 20, y);
  y += 6;
  if (sale.is_cash_paid) {
    doc.setTextColor(0, 128, 0);
    doc.setFont('helvetica', 'bold');
    doc.text('✓ Payment: Cash Paid', 20, y);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
  }
  y += 12;

  // Calculate subtotal and discount
  const subtotal = sale.subtotal || sale.sales_items?.reduce((sum: number, item: any) => sum + item.subtotal, 0) || sale.total_amount;
  const discountAmount = sale.discount_amount || 0;

  // Items table header
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Items', 20, y);
  y += 8;

  // Table header background (using theme muted color)
  doc.setFillColor(249, 250, 251);
  doc.rect(20, y - 5, 170, 8, 'F');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Product', 22, y);
  doc.text('Qty', 110, y);
  doc.text('Price', 135, y);
  doc.text('Subtotal', 170, y, { align: 'right' });
  y += 2;
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, 190, y);
  y += 8;

  // Items
  doc.setFont('helvetica', 'normal');
  let pageNum = 1;
  sale.sales_items?.forEach((item: any, index: number) => {
    if (y > 250) {
      addFooter(doc, pageNum, totalPages);
      doc.addPage();
      pageNum++;
      totalPages++;
      y = addCompanyHeader(doc, 'Sales Invoice');
    }
    doc.setFontSize(9);
    doc.text(item.finished_products?.name || 'Unknown', 22, y);
    doc.text(item.quantity.toString(), 110, y);
    doc.text(`PKR ${item.unit_price.toFixed(2)}`, 135, y);
    doc.text(`PKR ${item.subtotal.toFixed(2)}`, 190, y, { align: 'right' });

    // Alternate row background for better readability
    if (index % 2 === 0) {
      doc.setFillColor(249, 250, 251);
      doc.rect(20, y - 4, 170, 6, 'F');
      doc.setTextColor(0, 0, 0);
    }

    y += 7;
  });

  y += 5;
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, 190, y);
  y += 10;

  // Subtotal
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Subtotal:', 150, y);
  doc.text(`PKR ${subtotal.toFixed(2)}`, 190, y, { align: 'right' });
  y += 7;

  // Discount
  if (discountAmount > 0) {
    const discountType = sale.discount_type === 'percentage' ? '%' : 'PKR';
    const discountValue = sale.discount_value || 0;
    doc.setTextColor(220, 38, 38);
    doc.text(`Discount (${sale.discount_type === 'percentage' ? `${discountValue}%` : `PKR ${discountValue.toFixed(2)}`}):`, 150, y);
    doc.text(`- PKR ${discountAmount.toFixed(2)}`, 190, y, { align: 'right' });
    doc.setTextColor(0, 0, 0);
    y += 7;
  }

  // Total
  doc.setDrawColor(100, 100, 100);
  doc.setLineWidth(0.5);
  doc.line(20, y, 190, y);
  y += 8;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Total Amount:', 150, y);
  // Use theme primary color
  doc.setFillColor(139, 92, 246);
  doc.setTextColor(255, 255, 255);
  doc.rect(150, y - 6, 40, 8, 'F');
  doc.text(`PKR ${sale.total_amount.toFixed(2)}`, 190, y, { align: 'right' });
  doc.setTextColor(0, 0, 0);

  // Notes
  if (sale.notes) {
    y += 15;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Notes:', 20, y);
    y += 7;
    const splitNotes = doc.splitTextToSize(sale.notes, 170);
    doc.text(splitNotes, 20, y);
  }

  // Add footer
  addFooter(doc, pageNum, pageNum);

  return doc;
}

export function generateProductionRunPDF(run: any) {
  const doc = new jsPDF();
  let totalPages = 1;

  // Add header
  let y = addCompanyHeader(doc, 'Production Run');
  let pageNum = 1;

  doc.setFont('helvetica', 'bold');
  doc.text('Production Details', 20, y);
  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.text(`Run ID: ${run.id.slice(0, 8).toUpperCase()}`, 20, y);
  y += 6;
  doc.text(`Formulation: ${run.formulations?.name || 'Unknown'}`, 20, y);
  y += 6;
  doc.text(`Batch Size: ${run.batch_size} ${run.formulations?.batch_unit || 'kg'}`, 20, y);
  y += 6;
  doc.text(`Production Date: ${new Date(run.production_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 20, y);
  y += 10;

  // Materials Used
  doc.setFont('helvetica', 'bold');
  doc.text('Materials Used:', 20, y);
  y += 8;
  doc.setFillColor(249, 250, 251);
  doc.rect(20, y - 5, 170, 8, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Material', 22, y);
  doc.text('Quantity', 120, y);
  doc.text('Unit', 170, y);
  y += 2;
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, 190, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  run.production_materials_used?.forEach((mat: any, index: number) => {
    if (y > 250) {
      addFooter(doc, pageNum, totalPages);
      doc.addPage();
      pageNum++;
      totalPages++;
      y = addCompanyHeader(doc, 'Production Run');
    }
    doc.text(mat.raw_materials?.name || 'Unknown', 22, y);
    doc.text(mat.quantity_used.toFixed(3), 120, y);
    doc.text(mat.raw_materials?.unit || '', 170, y);
    y += 7;
  });

  y += 5;
  doc.line(20, y, 190, y);
  y += 10;

  // Finished Products
  if (run.finished_products_produced && run.finished_products_produced.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Finished Products Produced:', 20, y);
    y += 8;
    doc.setFillColor(249, 250, 251);
    doc.rect(20, y - 5, 170, 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Product', 22, y);
    doc.text('Quantity', 170, y, { align: 'right' });
    y += 2;
    doc.setDrawColor(200, 200, 200);
    doc.line(20, y, 190, y);
    y += 8;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    run.finished_products_produced.forEach((product: any) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      doc.text(product.name, 22, y);
      doc.text(`${product.quantity_produced} units`, 190, y, { align: 'right' });
      y += 7;
    });
  }

  if (run.notes) {
    y += 10;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Notes:', 20, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const splitNotes = doc.splitTextToSize(run.notes, 170);
    doc.text(splitNotes, 20, y);
  }

  // Add footer
  addFooter(doc, pageNum, pageNum);

  return doc;
}

export function generateLedgerPDF(customer: any, ledger: any[]) {
  const doc = new jsPDF();
  const totalPages = Math.ceil(ledger.length / 30) || 1; // Estimate pages

  // Add header
  let y = addCompanyHeader(doc, 'Customer Ledger');
  let pageNum = 1;

  // Customer details
  doc.setFontSize(12);
  doc.text(`Customer: ${customer.name}`, 20, y);
  y += 7;
  if (customer.email) {
    doc.text(`Email: ${customer.email}`, 20, y);
    y += 7;
  }
  if (customer.phone) {
    doc.text(`Phone: ${customer.phone}`, 20, y);
    y += 7;
  }
  y += 7;

  // Ledger table header
  doc.setFontSize(10);
  doc.text('Transaction History:', 20, y);
  y += 7;
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, 190, y);
  y += 5;

  doc.setFontSize(9);
  doc.text('Date', 20, y);
  doc.text('Type', 60, y);
  doc.text('Description', 90, y);
  doc.text('Amount', 140, y);
  doc.text('Balance', 170, y);
  y += 5;
  doc.line(20, y, 190, y);
  y += 7;

  // Ledger entries
  ledger.forEach((entry, index) => {
    if (y > 270) {
      addFooter(doc, pageNum, totalPages);
      doc.addPage();
      pageNum++;
      y = addCompanyHeader(doc, 'Customer Ledger');
      // Re-add customer info on new page
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(`Customer: ${customer.name}`, 20, y);
      y += 10;
      // Re-add table header
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Date', 20, y);
      doc.text('Type', 60, y);
      doc.text('Description', 90, y);
      doc.text('Amount', 140, y);
      doc.text('Balance', 170, y);
      y += 7;
      doc.setDrawColor(200, 200, 200);
      doc.line(20, y, 190, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
    }

    doc.text(new Date(entry.transaction_date).toLocaleDateString(), 20, y);
    doc.text(entry.transaction_type || 'Payment', 60, y);

    const description = entry.description || (entry.sale_id ? `Sale #${entry.sale_id?.slice(0, 8)}` : 'Payment');
    doc.text(description.length > 20 ? description.substring(0, 20) + '...' : description, 90, y);

    const amount = entry.amount || 0;
    const amountText = entry.transaction_type === 'payment' ? `-PKR ${Math.abs(amount).toFixed(2)}` : `PKR ${amount.toFixed(2)}`;
    doc.text(amountText, 140, y);
    doc.text(`PKR ${entry.balance.toFixed(2)}`, 170, y);
    y += 7;
  });

  // Final balance
  if (ledger.length > 0) {
    y += 5;
    doc.line(20, y, 190, y);
    y += 7;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    const finalBalance = ledger[ledger.length - 1]?.balance || 0;
    doc.text('Current Balance:', 140, y);
    doc.text(`PKR ${finalBalance.toFixed(2)}`, 170, y);
  }

  // Add footer
  addFooter(doc, pageNum, pageNum);

  return doc;
}

export function generateReportPDF(title: string, data: any, type: 'sales' | 'inventory' | 'production') {
  const doc = new jsPDF();

  // Add header
  let y = addCompanyHeader(doc, title);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');

  if (type === 'sales' && data.summary) {
    doc.text(`Total Sales: ${data.summary.totalSales}`, 20, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Revenue: PKR ${data.summary.totalRevenue.toFixed(2)}`, 20, y);
    y += 7;
    doc.text(`Total Items Sold: ${data.summary.totalItems}`, 20, y);
  } else if (type === 'inventory' && data.summary) {
    doc.text(`Raw Materials Value: PKR ${data.summary.rawMaterialsValue.toFixed(2)}`, 20, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.text(`Finished Products Value: PKR ${data.summary.finishedProductsValue.toFixed(2)}`, 20, y);
  } else if (type === 'production' && data.summary) {
    doc.text(`Total Production Runs: ${data.summary.totalRuns}`, 20, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Batch Size: ${data.summary.totalBatchSize.toFixed(2)}`, 20, y);
  }

  // Add footer
  addFooter(doc, 1, 1);

  return doc;
}

